---
- name: "Run Docker-Compose using ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running containers
    command: docker-compose down
    ignore_errors: yes
  
  - name: remove image built with dockercompose
    command: docker rmi laravel-app
    ignore_errors: yes

  - name: build docker-compose
    command: set -a

  - name: build docker-compose
    command: source .env

  - name: build docker-compose
    command: docker-compose up -d 




    
