---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop laravel-container
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm laravel-container
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi triple3a/laravel-app
    ignore_errors: yes
    
  - name: docker permission 
    command: sudo chmod 777 /var/run/docker.sock 

  - name: build docker image from dockerfile
    command: docker build -t triple3a/laravel-app .  

  - name: push image to dockerhub
    command: docker push triple3a/laravel-app 

  # - name: run container from image
  #   command: docker run -d --name laravel-container -p 5000:80 triple3a/laravel-app



  