apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
  namespace: laravel-app
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin
status:
  LoadBalancer: {}
